### ISSUE TITLE
datas_links -> links

### ISSUE THREAD

**Issue by Oros42** [PetitCitron/osd-api#1]
Salut
T'as du faire un mauvais chercher remplacé dans api/datas_annuaire.php.
Tu as mis `https://sebsauvage.net/datas_links/` au  lieu de `https://sebsauvage.net/links/`.
Idem pour `https://www.ecirtam.net/datas_links/` et d'autres.
Lignes 22, 26, 32, 36, 52, 56, 122 et 126.

Pour mon site (ecirtam.net), le `www` est inutile.

**Comment by PetitCitron** [comment]
Ah merde bien vu ! je vais corriger ça

**Comment by PetitCitron** [comment]
Merci @Oros42 ça doit être tout bon.

**Comment by Oros42** [comment]
> Merci @Oros42 ça doit être tout bon.

👍
